language: go

go:
  - 1.3
  - 1.4

env:
  - TURBO_VER="1.3.1"

before_install:
  - > 
      cd /tmp
      && wget http://downloads.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-official_${TURBO_VER}_amd64.deb
      && sudo dpkg -i libjpeg-turbo-official_${TURBO_VER}_amd64.deb
      && find /opt
      && export CGO_LDFLAGS="-L/opt/libjpeg-turbo/lib64"
      && export CGO_CFLAGS="-I/opt/libjpeg-turbo/include"
      && export LD_LIBRARY_PATH="/opt/libjpeg-turbo/lib64:$LD_LIBRARY_PATH"
  - cd $HOME/gopath/src/github.com/pixiv/go-libjpeg
